### ISSUE TITLE
How to generate a Hipchat token?

### ISSUE THREAD

**Issue by pepasflo** [blaskovicz/slack-hipchat-bridge#4]
I've read this page 3 times and I just can't seem to understand _how to actually get a token_: https://developer.atlassian.com/server/hipchat/hipchat-rest-api-access-tokens/

Can you describe how you got your setup working?

Thanks!

**Comment by blaskovicz** [comment]
The doc you linked to me is for creating oauth access tokens which is a process like:
- create an integration with a callback url
- user makes a request to your app, which redirects to ask hipchat for a token grant
- user grants app permission and hipchat redirects back to your app with a code
- you take the code and your integration secret and sign the code, resulting in a token (and optionally a refresh token)

You could try the "Build your own integration" under yourdomain.hipchat.com/addons/? When I enter a name (eg: bridge) and select a channel (eg: general), it gives me an auth_token. I'm thinking I could then use `HIPCHAT_JID=my-username@chat.hipchat.com` and `HIPCHAT_PASSWORD=thatAuthToken`.

Alternatively, you could just try setting `HIPCHAT_PASSWORD` to your account password; I think I had created a separate account at the time and just used that account username and that account password for those two variables.

I'm using HipBot::Bot (https://github.com/pewniak747/hipbot) password method to set the password, so you could see what they accept as well.

In any case, please let me know what you find and I can update my docs.

Thanks for checking.

**Comment by pepasflo** [comment]
Thanks!
